// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOsBSHGO3sCPQn9MdtX5HZgKFEHnwJors',
    appId: '1:541449199269:web:890bdd5f2cd08afa61374c',
    messagingSenderId: '541449199269',
    projectId: 'smartguardian-113d2',
    authDomain: 'smartguardian-113d2.firebaseapp.com',
    storageBucket: 'smartguardian-113d2.firebasestorage.app',
    measurementId: 'G-SK761J91ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbE8cAzmwNuFSeNoC437GrS9DvPxETig4',
    appId: '1:541449199269:android:9716bcacd3bbb50761374c',
    messagingSenderId: '541449199269',
    projectId: 'smartguardian-113d2',
    storageBucket: 'smartguardian-113d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0LOxRJXON3--FqOPj1JD1dJx5DSXf-I',
    appId: '1:541449199269:ios:fe3fd2b4788e08d561374c',
    messagingSenderId: '541449199269',
    projectId: 'smartguardian-113d2',
    storageBucket: 'smartguardian-113d2.firebasestorage.app',
    iosBundleId: 'com.example.smartguardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0LOxRJXON3--FqOPj1JD1dJx5DSXf-I',
    appId: '1:541449199269:ios:fe3fd2b4788e08d561374c',
    messagingSenderId: '541449199269',
    projectId: 'smartguardian-113d2',
    storageBucket: 'smartguardian-113d2.firebasestorage.app',
    iosBundleId: 'com.example.smartguardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOsBSHGO3sCPQn9MdtX5HZgKFEHnwJors',
    appId: '1:541449199269:web:3fe8ecdb94b4927161374c',
    messagingSenderId: '541449199269',
    projectId: 'smartguardian-113d2',
    authDomain: 'smartguardian-113d2.firebaseapp.com',
    storageBucket: 'smartguardian-113d2.firebasestorage.app',
    measurementId: 'G-202CDR4F2Y',
  );

}